import type { SurveyQuestion } from "./kursusleder-survey-types";

/** Standardspørgeskema baseret på Brandbjerg/Players 1st evaluering */
export function createDefaultSurveyQuestions(): SurveyQuestion[] {
  return [
    // Baggrundsspørgsmål
    {
      id: "bg-kursus",
      sectionTitle: "Baggrundsspørgsmål",
      type: "course_info",
      text: "Hvilket kursus deltager du på?",
      required: true,
      enabled: true,
    },
    {
      id: "bg-koen",
      sectionTitle: "Baggrundsspørgsmål",
      type: "single",
      text: "Angiv venligst dit køn",
      required: true,
      enabled: true,
      options: ["Mand", "Kvinde", "Nonbinær", "Ønsker ikke at svare"],
    },
    {
      id: "bg-alder",
      sectionTitle: "Baggrundsspørgsmål",
      type: "single",
      text: "Angiv venligst din alder",
      required: true,
      enabled: true,
      options: [
        "Under 50 år",
        "51 – 60 år",
        "61 – 70 år",
        "71 – 80 år",
        "81 – 90 år",
        "Over 90 år",
      ],
    },
    {
      id: "bg-valg-aarsag",
      sectionTitle: "Baggrundsspørgsmål",
      type: "multiple",
      text: "Hvilke af følgende elementer var afgørende for dig, da du valgte at tilmelde dig kurset på Brandbjerg Højskole? (sæt gerne op til 3 krydser)",
      required: false,
      enabled: true,
      maxSelections: 3,
      options: [
        "Kursets titel",
        "Det samlede program",
        "Specifikke programpunkter / undervisere",
        "Jeg havde fornemmelsen af, at der ville være en god stemning på Brandbjerg Højskole/kurset",
        "Brandbjerg højskole ligger godt i forhold til hvor jeg bor",
        "Brandbjerg Højskole ligger i naturskønne omgivelser",
        "At der er bad og toilet på værelset",
        "Mulighed for enkeltværelse",
        "Det passede lige med datoerne",
        "Prisen",
        "Jeg havde fået det anbefalet af venner/familie",
        "Har været på Brandbjerg før og ville gerne opleve det igen",
        "Andet",
      ],
    },
    {
      id: "bg-foer",
      sectionTitle: "Baggrundsspørgsmål",
      type: "single",
      text: "Har du været på kort kursus (ugekursus) på en højskole før?",
      required: false,
      enabled: true,
      options: [
        "Ja, jeg har været på et kort kursus Brandbjerg Højskole før",
        "Ja, jeg har været på et kort kursus på en (eller flere) andre højskoler før",
        "Nej, det er mit første korte kursus, men jeg har haft et længere ophold på højskole tidligere",
        "Nej, det er første gang, jeg er på højskole",
        "Andet",
      ],
    },

    // Overordnet tilfredshed
    {
      id: "ot-nps",
      sectionTitle: "Overordnet tilfredshed",
      sectionInstruction: "Baseret på din samlede oplevelse angiv venligst",
      type: "nps",
      text: "Hvor sandsynligt er det, at du vil anbefale Brandbjerg Højskole til familie, venner og omgangskreds?",
      required: true,
      enabled: true,
      scale: "likelihood",
      scaleMin: 0,
      scaleMax: 10,
    },
    {
      id: "ot-tilfreds",
      sectionTitle: "Overordnet tilfredshed",
      sectionInstruction: "Baseret på din samlede oplevelse angiv venligst",
      type: "interval",
      text: "Hvor tilfreds har du alt i alt været med kurset?",
      required: true,
      enabled: true,
      scale: "satisfaction",
      scaleMin: 1,
      scaleMax: 10,
    },
    {
      id: "ot-tilbage",
      sectionTitle: "Overordnet tilfredshed",
      sectionInstruction: "Baseret på din samlede oplevelse angiv venligst",
      type: "interval",
      text: "Hvor sandsynligt er det, at du kommer tilbage til Brandbjerg Højskole?",
      required: true,
      enabled: true,
      scale: "likelihood",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },

    // Programmet som helhed
    {
      id: "ph-program",
      sectionTitle: "Programmet som helhed",
      type: "interval",
      text: "Hvor tilfreds er du med det samlede program?",
      required: true,
      enabled: true,
      scale: "satisfaction",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "ph-tempo",
      sectionTitle: "Programmet som helhed",
      type: "single",
      text: "Hvordan oplevede du programmet?",
      required: true,
      enabled: true,
      options: ["For sløvt", "Passende", "For presset"],
    },

    // Specifikke programpunkter
    {
      id: "sp-velkomst",
      sectionTitle: "Specifikke programpunkter",
      type: "interval",
      text: "Hvor tilfreds var du med velkomst og rundvisning?",
      required: true,
      enabled: true,
      scale: "satisfaction",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "sp-morgen",
      sectionTitle: "Specifikke programpunkter",
      type: "interval",
      text: "Hvor tilfreds var du med ugens morgensamlinger?",
      required: false,
      enabled: true,
      scale: "satisfaction",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "sp-undervisning",
      sectionTitle: "Specifikke programpunkter",
      type: "interval",
      text: "Hvor tilfreds var du med ugens foredrag, workshops og undervisning?",
      required: false,
      enabled: true,
      scale: "satisfaction",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "sp-indtryk",
      sectionTitle: "Specifikke programpunkter",
      type: "text",
      text: "Var der noget i ugens program, der skilte sig ud eller gjorde særligt indtryk?",
      required: false,
      enabled: true,
      multiline: true,
    },
    {
      id: "sp-kommentar-undervisning",
      sectionTitle: "Specifikke programpunkter",
      type: "text",
      text: "Evt. kommentarer til ugens foredrag og undervisning?",
      required: false,
      enabled: true,
      multiline: true,
    },
    {
      id: "sp-hoejdepunkt",
      sectionTitle: "Specifikke programpunkter",
      type: "text",
      text: "Hvad var kursets højdepunkt for dig?",
      required: false,
      enabled: true,
      multiline: true,
    },
    {
      id: "sp-savnet",
      sectionTitle: "Specifikke programpunkter",
      type: "text",
      text: "Var der noget du savnede i programmet?",
      required: false,
      enabled: true,
      multiline: true,
    },
    {
      id: "sp-undvaere",
      sectionTitle: "Specifikke programpunkter",
      type: "text",
      text: "Var der noget der kunne undværes i programmet?",
      required: false,
      enabled: true,
      multiline: true,
    },
    {
      id: "sp-oevrige",
      sectionTitle: "Specifikke programpunkter",
      type: "text",
      text: "Har du øvrige kommentarer til programmet?",
      required: false,
      enabled: true,
      multiline: true,
    },

    // Kursusledelse og personale
    {
      id: "kl-ledelse",
      sectionTitle: "Kursusledelse og personale",
      type: "interval",
      text: "Hvor tilfreds var du med kursusledelsen?",
      required: true,
      enabled: true,
      scale: "satisfaction",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "kl-kommentar-ledelse",
      sectionTitle: "Kursusledelse og personale",
      type: "text",
      text: "Evt. kommentarer til kursusledelsen",
      required: false,
      enabled: true,
      multiline: true,
    },
    {
      id: "kl-personale",
      sectionTitle: "Kursusledelse og personale",
      type: "interval",
      text: "Jeg oplevede at personalet (køkken, pedel, kontor, rengøring mv.) på skolen var imødekommende og professionelle",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "kl-kommentar-personale",
      sectionTitle: "Kursusledelse og personale",
      type: "text",
      text: "Evt. kommentarer til personalet (køkken, pedel, kontor, rengøring m.m.)",
      required: false,
      enabled: true,
      multiline: true,
    },

    // Kursuslokaler og indeklima
    {
      id: "lo-lokaler",
      sectionTitle: "Kursuslokaler og indeklima",
      type: "interval",
      text: "Hvor tilfreds var du med kursuslokalerne?",
      required: true,
      enabled: true,
      scale: "satisfaction",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "lo-indeklima",
      sectionTitle: "Kursuslokaler og indeklima",
      type: "interval",
      text: "Hvor tilfreds var du med indeklimaet (rumtemperaturer, træk, udluftning og lignende)?",
      required: true,
      enabled: true,
      scale: "satisfaction",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "lo-kommentar",
      sectionTitle: "Kursuslokaler og indeklima",
      type: "text",
      text: "Evt. kommentarer til kursuslokaler og indeklima",
      required: false,
      enabled: true,
      multiline: true,
    },

    // Maden
    {
      id: "ma-mad",
      sectionTitle: "Maden",
      type: "interval",
      text: "Hvor tilfreds var du med maden?",
      required: true,
      enabled: true,
      scale: "satisfaction",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "ma-kommentar",
      sectionTitle: "Maden",
      type: "text",
      text: "Evt. kommentarer til ugens mad og forplejning",
      required: false,
      enabled: true,
      multiline: true,
    },

    // Værelset
    {
      id: "va-vaerelse",
      sectionTitle: "Værelset",
      type: "interval",
      text: "Hvor tilfreds var du med dit værelse?",
      required: true,
      enabled: true,
      scale: "satisfaction",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "va-kommentar",
      sectionTitle: "Værelset",
      type: "text",
      text: "Evt. kommentarer til værelset",
      required: false,
      enabled: true,
      multiline: true,
    },

    // Personligt udbytte
    {
      id: "pu-forventning",
      sectionTitle: "Personligt udbytte",
      type: "interval",
      text: "Jeg har til fulde fået indfriet mine forventninger til opholdet",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "pu-beriget",
      sectionTitle: "Personligt udbytte",
      type: "interval",
      text: "Jeg føler mig personligt beriget af opholdet",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "pu-inspireret",
      sectionTitle: "Personligt udbytte",
      type: "interval",
      text: "Opholdet har inspireret mig til at tænke eller handle anderledes",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },

    // Efterklang
    {
      id: "ef-indtryk",
      sectionTitle: "Efterklang",
      type: "interval",
      text: "Opholdet har gjort indtryk på mig",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "ef-hjem",
      sectionTitle: "Efterklang",
      type: "interval",
      text: "Jeg har fået noget med hjem, som jeg kan bruge i mit videre liv",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "ef-afbraek",
      sectionTitle: "Efterklang",
      type: "interval",
      text: "Jeg har fået et godt afbræk fra hverdagen, hvor jeg har kunnet koble fra og lade op",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },

    // Fællesskab
    {
      id: "fa-faellesskab",
      sectionTitle: "Fællesskab",
      type: "interval",
      text: "Jeg har følt mig som en del af et fællesskab",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "fa-atmosfaere",
      sectionTitle: "Fællesskab",
      type: "interval",
      text: "Jeg oplevede en varm og behagelig atmosfære",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },
    {
      id: "fa-samtaler",
      sectionTitle: "Fællesskab",
      type: "interval",
      text: "Jeg har haft spændende og inspirerende samtaler med mine medkursister",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },

    // Pris
    {
      id: "pr-pris",
      sectionTitle: "Pris for kurset",
      type: "interval",
      text: "Prisen for kurset er rimelig i forhold til den værdi, jeg har fået ud af det",
      required: true,
      enabled: true,
      scale: "agreement",
      scaleMin: 1,
      scaleMax: 10,
      allowNa: true,
    },

    // Yderligere
    {
      id: "sl-kommentar",
      sectionTitle: "Yderligere kommentarer",
      type: "text",
      text: "Hvis du har yderligere kommentarer kan du skrive dem her",
      required: false,
      enabled: true,
      multiline: true,
    },
  ];
}

export const DEFAULT_SURVEY_INTRODUCTION =
  "Tak fordi du tager dig tid til at fortælle os om din oplevelse. Det betyder meget for os, at du vil hjælpe, så vi kan gøre fremtidige kurser på Brandbjerg Højskole endnu bedre.";
